//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mess_management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cost
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cost()
        {
            this.UtilityBills = new HashSet<UtilityBill>();
        }
    
        public int costId { get; set; }
        public Nullable<int> messId { get; set; }
        public Nullable<int> userId { get; set; }
        public decimal totalCost { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual Mess Mess { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UtilityBill> UtilityBills { get; set; }
    }
}
