//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mess_management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manager
    {
        public int managerId { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<int> messId { get; set; }
    
        public virtual Mess Mess { get; set; }
    }
}
