//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mess_management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MealCount
    {
        public int mealId { get; set; }
        public Nullable<int> messId { get; set; }
        public Nullable<int> userId { get; set; }
        public int mealNum { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual Mess Mess { get; set; }
        public virtual User User { get; set; }
    }
}
