//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mess_management.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MessEntities1 : DbContext
    {
        public MessEntities1()
            : base("name=MessEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Cost> Costs { get; set; }
        public virtual DbSet<InventoryAssignment> InventoryAssignments { get; set; }
        public virtual DbSet<Manager> Managers { get; set; }
        public virtual DbSet<MealCount> MealCounts { get; set; }
        public virtual DbSet<MealDeposit> MealDeposits { get; set; }
        public virtual DbSet<Mess> Messes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UtilityBill> UtilityBills { get; set; }
    }
}
