//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mess_management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UtilityBill
    {
        public int utilityId { get; set; }
        public string utilityName { get; set; }
        public System.DateTime utilityDate { get; set; }
        public decimal cost { get; set; }
        public Nullable<int> costId { get; set; }
    
        public virtual Cost Cost1 { get; set; }
    }
}
